# Generated by Django 4.1 on 2022-09-11 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_phone_order_mob_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 11, 11, 47, 25, 787024)),
        ),
    ]
